weights: /content/yolov5-3.0/runs/exp0_HumpDump5m/weights/last.pt
cfg: yolov5m.yaml
data: data.yaml
hyp: data/hyp.finetune.yaml
epochs: 1500
batch_size: 16
img_size:
- 416
- 416
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
name: HumpDump5m
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
logdir: runs/
workers: 8
total_batch_size: 16
world_size: 1
global_rank: -1
